-- Codes à usage unique envoyés par SMS pour « mot de passe oublié »
CREATE TABLE code_reinitialisation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id bigint NOT NULL REFERENCES utilisateur (id) ON DELETE CASCADE,
    code_hache varchar(100) NOT NULL,
    expire_at timestamp NOT NULL,
    tentatives integer NOT NULL DEFAULT 0,
    utilise boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL
);
